# Generated by Django 3.2.9 on 2022-04-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=models.CharField(blank=True, default='https://bit.ly/3uAPmp5', max_length=256),
        ),
    ]
